### ISSUE TITLE
Missing files when installing kickbox 2.0.0 through pip

### ISSUE THREAD

**Issue by ginmrt** [kickboxio/kickbox-python#2]
I ran into an odd issue while trying to use kickbox 2.0.0. I installed it through pip as recommended but then ran into this ImportError:

``` bash
>>> import kickbox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ginmrt/virtualenvs/testkick200/lib/python2.7/site-packages/kickbox/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/ginmrt/virtualenvs/testkick200/lib/python2.7/site-packages/kickbox/client.py", line 1, in <module>
    from .http_client import HttpClient
ImportError: No module named http_client
```

I then noticed that version 1.0.3 does not have this problem, and that there seemed to be missing files when comparing the two versions in different virtualenvs:

**2.0.0**

``` bash
pip show --files kickbox

---
Metadata-Version: 1.1
Name: kickbox
Version: 2.0.0
Summary: Official kickbox API library client for python
Home-page: http://kickbox.io
Author: Chaitanya Surapaneni
Author-email: chaitanya.surapaneni@kickbox.io
License: MIT
Location: /Users/ginmrt/virtualenvs/testkick2/lib/python2.7/site-packages
Requires: requests
Files:
  kickbox-2.0.0-py2.7.egg-info
  kickbox-2.0.0-py2.7.egg-info/PKG-INFO
  kickbox-2.0.0-py2.7.egg-info/SOURCES.txt
  kickbox-2.0.0-py2.7.egg-info/dependency_links.txt
  kickbox-2.0.0-py2.7.egg-info/requires.txt
  kickbox-2.0.0-py2.7.egg-info/top_level.txt
  kickbox/__init__.py
  kickbox/__init__.pyc
  kickbox/client.py
  kickbox/client.pyc
```

**1.0.3**

``` bash
pip show --files kickbox

---
Metadata-Version: 1.1
Name: kickbox
Version: 1.0.3
Summary: Official kickbox API library client for python
Home-page: http://kickbox.io
Author: Chaitanya Surapaneni
Author-email: chaitanya.surapaneni@kickbox.io
License: MIT
Location: /Users/ginmrt/virtualenvs/testkick/lib/python2.7/site-packages
Requires: requests
Files:
  kickbox-1.0.3-py2.7.egg-info
  kickbox-1.0.3-py2.7.egg-info/PKG-INFO
  kickbox-1.0.3-py2.7.egg-info/SOURCES.txt
  kickbox-1.0.3-py2.7.egg-info/dependency_links.txt
  kickbox-1.0.3-py2.7.egg-info/requires.txt
  kickbox-1.0.3-py2.7.egg-info/top_level.txt
  kickbox/__init__.py
  kickbox/__init__.pyc
  kickbox/api/__init__.py
  kickbox/api/__init__.pyc
  kickbox/api/kickbox.py
  kickbox/api/kickbox.pyc
  kickbox/client.py
  kickbox/client.pyc
  kickbox/error/__init__.py
  kickbox/error/__init__.pyc
  kickbox/error/client_error.py
  kickbox/error/client_error.pyc
  kickbox/http_client/__init__.py
  kickbox/http_client/__init__.pyc
  kickbox/http_client/auth_handler.py
  kickbox/http_client/auth_handler.pyc
  kickbox/http_client/error_handler.py
  kickbox/http_client/error_handler.pyc
  kickbox/http_client/request_handler.py
  kickbox/http_client/request_handler.pyc
  kickbox/http_client/response.py
  kickbox/http_client/response.pyc
  kickbox/http_client/response_handler.py
  kickbox/http_client/response_handler.pyc
```

Is something wrong with version 2.0.0's build?

**Comment by AlexandreArpin** [comment]
+1

Oddly enough, the packages on pypi are fine if you download the sources manually.

https://pypi.python.org/pypi/kickbox/2.0.0
https://pypi.python.org/pypi/kickbox/1.0.3

**Comment by danhstevens** [comment]
Thanks for the pull request, @ginmrt!
