### ISSUE TITLE
Giving an Error

### ISSUE THREAD

**Issue by gautam12354** [kickboxio/kickbox-python#8]
```python
response = kickbox.verify("gautamk780@gmail.com")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\kickbox\api\kickbox.py", line 24, in verify
    response = self.client.get('/verify?email=' + email + '&timeout=' + str(timeout), body, options)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\kickbox\http_client\__init__.py", line 47, in get
    return self.request(path, None, 'get', options)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\kickbox\http_client\__init__.py", line 97, in request
    response = self.create_request(method, path, kwargs)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\kickbox\http_client\__init__.py", line 118, in create_request
    return requests.request(method, path, **options)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Users\Gautam Kumar Pandey\AppData\Roaming\Python\Python37\site-packages\kickbox\http_client\error_handler.py", line 34, in check_error
    raise ClientError(message, code)
kickbox.error.client_error.ClientError
```

**Comment by schaitanya** [comment]
Please make sure you're providing the correct API key and are handling the exceptions properly.

```python
import kickbox

client = kickbox.Client("MY_API_KEY")
kickbox = client.kickbox()

try:
    response = kickbox.verify("test@test.com")
    print response.body
except Exception as e:
    print e.message
```

If this did not fix the issue, please provide the failing code (removing the sensitive data).

**Comment by schaitanya** [comment]
Please feel free to open if the issue persists.
